version: '2'
services:
    etcd0:
        image: quay.io/coreos/etcd:v2.3.8
        # command:
        environment:
            HostIP: "10.130.172.153"
            advertise-client-urls: http://${HostIP}:2379,http://${HostIP}:4001
            listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
            initial-advertise-peer-urls: http://${HostIP}:2380
            listen-peer-urls: http://0.0.0.0:2380
            initial-cluster-token: etcd-cluster-1
            initial-cluster: etcd0=http://${HostIP}:2380
            initial-cluster-state: new
            name: etcd
        command:
            "-name etcd0 \
            -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
            -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
            -initial-advertise-peer-urls http://${HostIP}:2380 \
            -listen-peer-urls http://0.0.0.0:2380 \
            -initial-cluster-token etcd-cluster-1 \
            -initial-cluster etcd0=http://${HostIP}:2380 \
            -initial-cluster-state new"

        #     "initial-cluster-state": "new"
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        # #     args:
        # #         HostIP: 192.168.1.175
        # #         xxx: yyyy
        volumes:
            # v /usr/share/ca-certificates/:/etc/ssl/certs
            - /usr/share/ca-certificates:/etc/ssl/certs
        ports:
            - "4001:4001"
            - "2380:2380"
            - "2379:2379"

    etcd_viewer:
        image: nikfoundas/etcd-viewer
        ports:
            - "8080:8080"

# volumes:
#     ca-certificates:
