version: '3'
services:
    jenkins.docker:
        image: shimmi/jenkins
        ports:
            - "8080:8080"
        volumes:
            - /home/pav/worka/docker/docker_compose/jenkins/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
