version: '3'
services:
    jenkins.docker:
        image: shimmi/jenkins
        ports:
            - "8080:8080"
        # volumes:
            # - /Users/pav/Documents/Worka/GitRepo/pv_repo/docker_compose/jenkins:/var/jenkins_home
            # - /var/run/docker.sock:/var/run/docker.sock
